services:
  api-service:
    image: rag-project-v1:latest
    container_name: rag-backend
    ports:
      - "8000:8000"
    env_file: .env
    command: python api.py

  ui-service:
    image: rag-project-v1:latest
    container_name: rag-frontend
    ports:
      - "8501:8501"
    env_file: .env
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0